name: Build Zink (OSMesa 24.0.5) for iOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: install packed
        run: |
          brew install meson ninja bison flex pkg-config wget vulkan-headers

      - name: install MoltenVK 1.4.1
        run: |
          git clone --branch v1.4.1 https://github.com/KhronosGroup/MoltenVK.git

      - name: install and untar.xz Mesa 24.0.5
        run: |
          wget https://archive.mesa3d.org/mesa-24.0.5.tar.xz
          tar -xf mesa-24.0.5.tar.xz

      - name: create setting Build for iPhone (arm64)
        run: |
          IOS_SDK=$(xcrun --sdk iphoneos --show-sdk-path)
          
          cat <<EOF > ios.ini
          [binaries]
          c = 'clang'
          cpp = 'clang++'
          objc = 'clang'
          objcpp = 'clang++'
          ar = 'ar'
          strip = 'strip'

          [built-in options]
          c_args = ['-arch', 'arm64', '-isysroot', '$IOS_SDK', '-miphoneos-version-min=15.0', '-I${{ github.workspace }}/MoltenVK/MoltenVK/icd']
          cpp_args = ['-arch', 'arm64', '-isysroot', '$IOS_SDK', '-miphoneos-version-min=15.0', '-I${{ github.workspace }}/MoltenVK/MoltenVK/icd']
          c_link_args = ['-arch', 'arm64', '-isysroot', '$IOS_SDK', '-miphoneos-version-min=15.0', '-framework', 'Foundation', '-framework', 'Metal']
          cpp_link_args = ['-arch', 'arm64', '-isysroot', '$IOS_SDK', '-miphoneos-version-min=15.0', '-framework', 'Foundation', '-framework', 'Metal']

          [host_machine]
          system = 'darwin'
          subsystem = 'ios'
          cpu_family = 'aarch64'
          cpu = 'arm64'
          endian = 'little'
          EOF

      - name: setting Meson (OSMesa)
        run: |
          cd mesa-24.0.5
          meson setup build_ios \
            --cross-file ../ios.ini \
            -Dbuildtype=release \
            -Dgallium-drivers=zink \
            -Dvulkan-drivers= \
            -Dglx=disabled \
            -Degl=disabled \
            -Dosmesa=true \
            -Dllvm=disabled

      - name: running Ninja (compile)
        run: |
          cd mesa-24.0.5/build_ios
          ninja

      - name: upload file dylib
        uses: actions/upload-artifact@v4
        with:
          name: libOSMesa-iOS
          path: mesa-24.0.5/build_ios/src/gallium/targets/osmesa/libOSMesa.*dylib